version: "3.4"

services:
  bookingbridgebackend:
    image: bookingbridgebackend
    build:
      context: .
      dockerfile: ./Dockerfile
      ports:
        - 8080:8080
    environment:
      environment:
      NODE_ENV: production
      DATABASE_USER: ${DOCKER_DATABASE_USER}
      DATABASE_NAME: ${DOCKER_DATABASE_NAME}
      DATABASE_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
      POSTGRES_USER: ${DOCKER_DATABASE_USER}
      POSTGRES_NAME: ${DOCKER_DATABASE_NAME}
      POSTGRES_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${DOCKER_DATABASE_HOST_AUTH_METHOD}
